<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BigML">
  <eClassifiers xsi:type="ecore:EClass" name="BigML Model" eSuperTypes="#//BigMLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipelines" upperBound="-1"
        eType="#//Pipeline" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//BigMLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedPorts" upperBound="-1"
        eType="#//ProvidedPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalComponent" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeInternalComponent"
        upperBound="-1" eType="#//InternalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPorts" upperBound="-1"
        eType="#//RequiredPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalComponent" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//BigMLElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline" eSuperTypes="#//BigMLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedPort" lowerBound="1"
        eType="#//ProvidedPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPort" lowerBound="1"
        eType="#//RequiredPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigMLElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataProcessor" eSuperTypes="#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="StorageSystem" eSuperTypes="#//InternalComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessRights" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataVisualizer" eSuperTypes="#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageQueue" eSuperTypes="#//InternalComponent"/>
</ecore:EPackage>
